In [378]:
# - import libraries
# - load dataset
# - explore dataset

# - fix column names
# - fix individual columns

# - fix nulls in all type of columns
# - fix duplicates in all type of columns
# - fix outliers
# - fix logical intigrity
# - final exploration
# - save cleaned data

### 1. Import required libraries

In [379]:
import numpy as np
import pandas as pd

### 2. Load dataset

In [380]:
df = pd.read_csv(r"C:\Users\Arijit\Downloads\archive\Airbnb_Open_Data.csv", low_memory=False)
df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

### 3. Explore dataset

In [381]:
print("\nTotal rows : ", df.shape[0])
print("\nTotal columns : ", df.shape[1])
print("\nDataset size : ", df.size)
print("Info about dataset : \n", df.info())

Total rows :  102599

Total columns :  26

Dataset size :  2667574
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB
Info about dataset :
 None

In [382]:
df.describe()

,id,host id,lat,long,Construction year,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,1.025990e+05,1.025990e+05,102591.000000,102591.000000,102385.000000,102190.000000,102416.000000,86720.000000,102273.000000,102280.000000,102151.000000
mean,2.914623e+07,4.925411e+10,40.728094,-73.949644,2012.487464,8.135845,27.483743,1.374022,3.279106,7.936605,141.133254
std,1.625751e+07,2.853900e+10,0.055857,0.049521,5.765556,30.553781,49.508954,1.746621,1.284657,32.218780,135.435024
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,2003.000000,-1223.000000,0.000000,0.010000,1.000000,1.000000,-10.000000
25%,1.508581e+07,2.458333e+10,40.688740,-73.982580,2007.000000,2.000000,1.000000,0.220000,2.000000,1.000000,3.000000
50%,2.913660e+07,4.911774e+10,40.722290,-73.954440,2012.000000,3.000000,7.000000,0.740000,3.000000,1.000000,96.000000
75%,4.320120e+07,7.399650e+10,40.762760,-73.932350,2017.000000,5.000000,30.000000,2.000000,4.000000,2.000000,269.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,2022.000000,5645.000000,1024.000000,90.000000,5.000000,332.000000,3677.000000

### 4. Fix column names

In [383]:
# Step 1 - Explore columns
print(df.columns)

print("\nTotal columns : ", df.shape[1])
print("\nTotal duplicated columns : ", df.columns.duplicated().sum())
print("\nTotal unique columns : ", df.columns.nunique())

print("\nSpecial character containing columns : ", df.columns[df.columns.str.contains(r'[^A-Za-z0-9\s]')])
print("\nNumbers containing columns : ", df.columns[df.columns.str.contains(r'[0-9]')])
print("\nUpper case letters containing columns : ", df.columns[df.columns != df.columns.str.lower()])
print("\nLeft-right side Space containing columns : ", df.columns[df.columns != df.columns.str.strip()])
print("\nTotal Inner space containing columns : ", df.columns[df.columns.str.contains(' ')].nunique())

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

Total columns :  26

Total duplicated columns :  0

Total unique columns :  26

Special character containing columns :  Index(['host_identity_verified', 'instant_bookable', 'cancellation_policy',
       'house_rules'],
      dtype='object')

Numbers containing columns :  Index(['availability 365'], dtype='object')

Upper case letters containing columns :  Index(['NAME', 'Construction year'], dtype='object')

Left-right side Space containing columns :  Index([], dtype='object')

Total Inner space containing columns :  14

In [384]:
# Step 2 - Fix erros in those columns

df.columns = (
    df.columns
    .str.lower()
    .str.replace(' ', '_')
    .str.replace(r'[^A-Za-z_]', '', regex=True)
)

# Final Check
print("\nSpecial character containing columns : ", df.columns[df.columns.str.contains(r'[^A-Za-z0-9\s]')])
print("\nNumbers containing columns : ", df.columns[df.columns.str.contains(r'[0-9]')])
print("\nUpper case letters containing columns : ", df.columns[df.columns != df.columns.str.lower()])
print("\nTotal Inner space containing columns : ", df.columns[df.columns.str.contains(' ')].nunique())

print(df.columns)

Special character containing columns :  Index(['host_id', 'host_identity_verified', 'host_name', 'neighbourhood_group',
       'country_code', 'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'service_fee', 'minimum_nights',
       'number_of_reviews', 'last_review', 'reviews_per_month',
       'review_rate_number', 'calculated_host_listings_count', 'availability_',
       'house_rules'],
      dtype='object')

Numbers containing columns :  Index([], dtype='object')

Upper case letters containing columns :  Index([], dtype='object')

Total Inner space containing columns :  0
Index(['id', 'name', 'host_id', 'host_identity_verified', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'lat', 'long', 'country',
       'country_code', 'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'price', 'service_fee', 'minimum_nights',
       'number_of_reviews', 'last_review', 'reviews_per_month',
       'review_rate_number', 'calculated_host_listings_count', 'availability_',
       'house_rules', 'license'],
      dtype='object')

In [385]:
# drop columns which is not important
columns_to_drop = [
    'reviews_per_month',
    'review_rate_number', 
    'calculated_host_listings_count', 
    'availability_',
    'house_rules', 
    'license', 
    'country_code', 
    'last_review'
]

df.drop(columns=columns_to_drop, inplace=True)
print("Total columns : ", df.shape[1])
print(df.columns)

Total columns :  18
Index(['id', 'name', 'host_id', 'host_identity_verified', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'lat', 'long', 'country',
       'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'price', 'service_fee', 'minimum_nights',
       'number_of_reviews'],
      dtype='object')

## 5. Fix individual columns
###    - Fix object type columns
###    - Fix int type columns

In [386]:
# Fix object type columns
# Step 1 - Explore every columns one by one

for column in df.columns:
    if df[column].dtype == "object":
        print(column)

name
host_identity_verified
host_name
neighbourhood_group
neighbourhood
country
instant_bookable
cancellation_policy
room_type
price
service_fee

In [387]:
for column in df.columns:

    if df[column].dtype == "object":

        if column == "instant_bookable":
            continue

        # Check for special characters - "!@#$%^&*()+-=[]{}|;':\",./<>?`~\\"
        print(
            f"Special characters in {column}: ",
            df[column].astype(str).str.contains(
                r'[^A-Za-z0-9\s]', regex=True, na=False
            ).sum()
        )

        # Check for numbers
        print(
            f"Numbers in {column}: ",
            df[column].astype(str).str.contains(
                r'[0-9]', regex=True, na=False
            ).sum()
        )

        # Check for Leading and trailing spaces in a string
        mask_spaces = df[column].notna() & (df[column] != df[column].str.strip())
        print(f"Spaces in {column} : ", mask_spaces.sum())

        # Check for upper case letters
        print(
            f"Uppercase-containing values in {column}: ",
            df[column].astype(str).str.contains(
                r'[A-Z]', regex=True, na=False
            ).sum()
        )

        print()

Special characters in name:  56821
Numbers in name:  34063
Spaces in name :  44
Uppercase-containing values in name:  101098

Special characters in host_identity_verified:  0
Numbers in host_identity_verified:  0
Spaces in host_identity_verified :  0
Uppercase-containing values in host_identity_verified:  0

Special characters in host_name:  4713
Numbers in host_name:  134
Spaces in host_name :  0
Uppercase-containing values in host_name:  102074

Special characters in neighbourhood_group:  0
Numbers in neighbourhood_group:  0
Spaces in neighbourhood_group :  0
Uppercase-containing values in neighbourhood_group:  102568

Special characters in neighbourhood:  13438
Numbers in neighbourhood:  0
Spaces in neighbourhood :  0
Uppercase-containing values in neighbourhood:  102583

Special characters in country:  0
Numbers in country:  0
Spaces in country :  0
Uppercase-containing values in country:  102067

Special characters in cancellation_policy:  0
Numbers in cancellation_policy:  0
Spaces in cancellation_policy :  0
Uppercase-containing values in cancellation_policy:  0

Special characters in room_type:  53701
Numbers in room_type:  0
Spaces in room_type :  0
Uppercase-containing values in room_type:  102599

Special characters in price:  102352
Numbers in price:  102352
Spaces in price :  102352
Uppercase-containing values in price:  0

Special characters in service_fee:  102326
Numbers in service_fee:  102326
Spaces in service_fee :  102326
Uppercase-containing values in service_fee:  0

In [388]:
# Special characters in name:  56821
# Numbers in name:  34063
# Leading/Trailing spaces in name:  294
# Uppercase-containing values in name:  101098

# Fix for column - name
df['name'] = (
    df['name']
    .str.strip()
    .str.lower()
    .str.replace(r'[^a-z\s]', '', regex=True)
    .str.strip()
)

In [389]:
# Check
print(df['name'].astype(str).str.contains(r'[^a-z\s]', regex=True).sum())
print(df['name'].astype(str).str.contains(r'[0-9]', regex=True).sum())

# We have to check those rows which contains values and not contains any leading/trailing spaces
mask_space = df['name'].notna() & (df['name'] != df['name'].str.strip())
print(mask_space.sum())

print(df['name'].astype(str).str.contains(r'[A-Z]', regex=True).sum())

0
0
0
0

In [390]:
# Special characters in host_name:  4713
# Numbers in host_name:  134
# Spaces in host_name :  0
# Uppercase-containing values in host_name:  102074

# Fix
df['host_name'] = (
    df['host_name']
    .str.lower()
    .str.replace(r'[^a-z\s]', '', regex=True)
)

In [391]:
# Check 

# Special Characters
print(df['host_name'].astype(str).str.contains(r'[^a-z\s]').sum())

# Numbers
print(df['host_name'].astype(str).str.contains(r'[0-9]').sum())

# Upper case containing letters
# One method
mask_upper = df['host_name'].notna() & (df['host_name'] != df['host_name'].str.lower())
print(mask_upper.sum())

# another method to check upper letter
print(df['host_name'].astype(str).str.contains(r'[A-Z]').sum())

0
0
0
0

In [392]:
# Special characters in neighbourhood_group:  0
# Numbers in neighbourhood_group:  0
# Spaces in neighbourhood_group :  0
# Uppercase-containing values in neighbourhood_group:  102568

df['neighbourhood_group'] = (
    df['neighbourhood_group']
    .str.lower()
)

print(df['neighbourhood_group'].unique())
print(df['neighbourhood_group'].value_counts())

df['neighbourhood_group'] = df['neighbourhood_group'].replace(
    {
        "manhatan" : "manhattan",
        "brookln": "brooklyn"
    }
)

print(df['neighbourhood_group'].unique())
print(df['neighbourhood_group'].value_counts())

['brooklyn' 'manhattan' 'brookln' 'manhatan' 'queens' nan 'staten island'
 'bronx']
neighbourhood_group
manhattan        43792
brooklyn         41842
queens           13267
bronx             2712
staten island      955
brookln              1
manhatan             1
Name: count, dtype: int64
['brooklyn' 'manhattan' 'queens' nan 'staten island' 'bronx']
neighbourhood_group
manhattan        43793
brooklyn         41843
queens           13267
bronx             2712
staten island      955
Name: count, dtype: int64

In [393]:
mask_upper = df['neighbourhood_group'].notna() & (df['neighbourhood_group'] != df['neighbourhood_group'].str.lower())
print(mask_upper.sum())

print(df['neighbourhood_group'].astype(str).str.contains(r'[A-Z]', regex=True).sum())

0
0

In [394]:
# Special characters in neighbourhood:  13438
# Numbers in neighbourhood:  0
# Spaces in neighbourhood :  0
# Uppercase-containing values in neighbourhood:  102583

df['neighbourhood'] = (
    df['neighbourhood']
    .str.lower()
    .str.replace(r'[^a-z\s]', '', regex=True)
)
df['neighbourhood'].value_counts()

neighbourhood
bedfordstuyvesant        7937
williamsburg             7775
harlem                   5466
bushwick                 4982
hells kitchen            3965
                         ...
rossville                   3
gerritsen beach             3
fort wadsworth              2
glen oaks                   2
chelsea staten island       1
Name: count, Length: 224, dtype: int64

In [395]:
# Fix

# Check special character
print(df['neighbourhood'].astype(str).str.contains(r'[^a-z\s]', regex=True, na=False).sum())

# Check for upper case letters
print(df['neighbourhood'].astype(str).str.contains(r'[A-Z]', regex=True, na=False).sum())

0
0

In [396]:
# Special characters in country:  0
# Numbers in country:  0
# Spaces in country :  0
# Uppercase-containing values in country:  102067

df['country'] = (
    df['country']
    .str.lower()
)

print(df['country'].unique())
print(df['country'].value_counts())

['united states' nan]
country
united states    102067
Name: count, dtype: int64

In [397]:
# Special characters in room_type:  53701
# Numbers in room_type:  0
# Spaces in room_type :  0
# Uppercase-containing values in room_type:  102599

df['room_type'] = (
    df['room_type']
    .str.lower()
    .str.replace(r'[^a-z\s]', '', regex=True)
)

print(df['room_type'].unique())
print(df['room_type'].value_counts())

['private room' 'entire homeapt' 'shared room' 'hotel room']
room_type
entire homeapt    53701
private room      46556
shared room        2226
hotel room          116
Name: count, dtype: int64

In [398]:
# Special characters in price:  102352
# Numbers in price:  102352
# Spaces in price :  102352
# Uppercase-containing values in price:  0

df['price'] = df['price'].str.replace(r'[^0-9]', '', regex=True)
df['price'] = df['price'].fillna(df['price'].mode()[0])
df['price'] = df['price'].astype(int)

In [399]:
# Special characters in service_fee:  102326
# Numbers in service_fee:  102326
# Spaces in service_fee :  102326
# Uppercase-containing values in service_fee:  0

df['service_fee'] = df['service_fee'].str.replace(r'[^0-9]', '', regex=True)
df['service_fee'] = df['service_fee'].fillna(df['service_fee'].mode()[0])
df['service_fee'] = df['service_fee'].astype(str).astype(int)

### 6. Fix nulls in all type of columns

#####  - We have to fix nulls in every type of columns such as int64, object, float64, bool

In [400]:
df

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,1001254,clean quiet apt home by the park,80014485718,unconfirmed,madaline,brooklyn,kensington,40.64749,-73.97237,united states,False,strict,private room,2020.0,966,193,10.0,9.0
1,1002102,skylit midtown castle,52335172823,verified,jenna,manhattan,midtown,40.75362,-73.98377,united states,False,moderate,entire homeapt,2007.0,142,28,30.0,45.0
2,1002403,the village of harlemnew york,78829239556,NaN,elise,manhattan,harlem,40.80902,-73.94190,united states,True,flexible,private room,2005.0,620,124,3.0,0.0
3,1002755,NaN,85098326012,unconfirmed,garry,brooklyn,clinton hill,40.68514,-73.95976,united states,True,moderate,entire homeapt,2005.0,368,74,30.0,270.0
4,1003689,entire apt spacious studioloft by central park,92037596077,verified,lyndon,manhattan,east harlem,40.79851,-73.94399,united states,False,moderate,entire homeapt,2009.0,204,41,10.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,spare room in williamsburg,12312296767,verified,krik,brooklyn,williamsburg,40.70862,-73.94651,united states,False,flexible,private room,2003.0,844,169,1.0,0.0
102595,6092990,best location near columbia u,77864383453,unconfirmed,mifan,manhattan,morningside heights,40.80460,-73.96545,united states,True,moderate,private room,2016.0,837,167,1.0,1.0
102596,6093542,comfy bright room in brooklyn,69050334417,unconfirmed,megan,brooklyn,park slope,40.67505,-73.98045,united states,True,moderate,private room,2009.0,988,198,3.0,0.0
102597,6094094,big studioone stop from midtown,11160591270,unconfirmed,christopher,queens,long island city,40.74989,-73.93777,united states,True,strict,entire homeapt,2015.0,546,109,2.0,5.0
102598,6094647,sf luxury studio,68170633372,unconfirmed,rebecca,manhattan,upper west side,40.76807,-73.98342,united states,False,flexible,entire homeapt,2010.0,1032,206,1.0,0.0

### Type -  int64 & float64

In [401]:
# Steps -
# - Check missing percentage
# - If 50 % or above data is missing then drop the column if it is not important
# - Or,
# - Check outlier in each column
# - If outlier present , replace NaN values with median
# - If outlier is not present, replace NaN values with mean

In [402]:
# Check missing percentage
for column in df.columns:
    if df[column].dtypes == "int64" or df[column].dtypes =="float64":
        missing_pct = np.trunc(df[column].isnull().sum()/len(df))*100
        print(column, "(", df[column].isnull().sum(), ",", missing_pct,"%", ")")

id ( 0 , 0.0 % )
host_id ( 0 , 0.0 % )
lat ( 8 , 0.0 % )
long ( 8 , 0.0 % )
construction_year ( 214 , 0.0 % )
price ( 0 , 0.0 % )
service_fee ( 0 , 0.0 % )
minimum_nights ( 409 , 0.0 % )
number_of_reviews ( 183 , 0.0 % )

In [403]:
# Function of checking outliers
def is_outlier(col: str, df: pd.DataFrame) -> bool:

    Q1 = df[col].quantile(0.25) # Lower quantile -> 25 %
    Q2 = df[col].median()       # Median -> 50 %
    Q3 = df[col].quantile(0.75) # Upper auantile -> 75 %

    IQR = Q3 - Q1 # IQR

    lower_limit = Q1 - (IQR * 1.5)
    upper_limit = Q3 + (IQR * 1.5)

    if len(df.loc[df[col] < lower_limit]) > 0 or len(df.loc[df[col] > upper_limit]) > 0:
        return True
    else:
        return False

In [404]:
# Fixing nulls
for column in df.columns:
    if df[column].dtypes == "int64" or df[column].dtypes =="float64":
        missing_pct = np.trunc(df[column].isnull().sum()/len(df))*100

        if missing_pct <= 50:
            if is_outlier(col=column, df=df):
                df[column] = df[column].replace(np.nan, df[column].median())
            else:
                df[column] = df[column].replace(np.nan, df[column].mean())

In [405]:
# Final check
for column in df.columns:
    if df[column].dtypes == "int64" or df[column].dtypes =="float64":
        missing_pct = np.trunc(df[column].isnull().sum()/len(df))*100
        print(column, "(", df[column].isnull().sum(), ",", missing_pct,"%", ")")

id ( 0 , 0.0 % )
host_id ( 0 , 0.0 % )
lat ( 0 , 0.0 % )
long ( 0 , 0.0 % )
construction_year ( 0 , 0.0 % )
price ( 0 , 0.0 % )
service_fee ( 0 , 0.0 % )
minimum_nights ( 0 , 0.0 % )
number_of_reviews ( 0 , 0.0 % )

### Type - object

In [406]:
# Steps -
# - Check missing percentage
# - If 50 % or above data is missing then drop the column if it is not important
# - Or,
# - Fill it with 'unknown'
# - If missing percentage <= 10, fill NaN with most frequent value of the column using mode

In [407]:
# Check missing percentage
for column in df.columns:
    if df[column].dtypes == "object":
        missing_pct = np.trunc(df[column].isnull().sum()/len(df))*100
        print(column, "(", df[column].isnull().sum(), ",", missing_pct,"%", ")")

name ( 250 , 0.0 % )
host_identity_verified ( 289 , 0.0 % )
host_name ( 406 , 0.0 % )
neighbourhood_group ( 29 , 0.0 % )
neighbourhood ( 16 , 0.0 % )
country ( 532 , 0.0 % )
instant_bookable ( 105 , 0.0 % )
cancellation_policy ( 76 , 0.0 % )
room_type ( 0 , 0.0 % )

In [ ]:
for column in df.columns:
    if df[column].dtypes == "object":
        missing_pct = np.trunc(df[column].isnull().sum()/len(df))*100

        if missing_pct <= 10:
            df[column] = df[column].replace(np.nan, df[column].mode()[0])
        else:
            df[column].fillna('unknown', inplace=True)

In [409]:
# Final check
df.isnull().sum()

id                        0
name                      0
host_id                   0
host_identity_verified    0
host_name                 0
neighbourhood_group       0
neighbourhood             0
lat                       0
long                      0
country                   0
instant_bookable          0
cancellation_policy       0
room_type                 0
construction_year         0
price                     0
service_fee               0
minimum_nights            0
number_of_reviews         0
dtype: int64

## 7. Fix duplicates in all type of columns

In [410]:
# Check duplicates
# Drop if it is logicless
# Or keep it
# It is not mandatory to drop all duplicates, most of the time it is important for getting valuable insights.

In [411]:
# Check
for column in df.columns:
    print(column, "=", df[column].duplicated().sum())

id = 541
name = 43714
host_id = 542
host_identity_verified = 102597
host_name = 89598
neighbourhood_group = 102594
neighbourhood = 102375
lat = 80608
long = 84825
country = 102598
instant_bookable = 102597
cancellation_policy = 102596
room_type = 102595
construction_year = 102578
price = 101448
service_fee = 102368
minimum_nights = 102446
number_of_reviews = 102123

In [412]:
# Check id and name
# An unique id can only contain a unique name, it should not contain duplicates

# You have to drop if it is not,
"""
mask = df.groupby('id')['name'].transform('nunique') > 1
df.drop(df[mask].index, inplace=True)
"""


df.groupby('id')['name'].nunique()

id
1001254     1
1002102     1
1002403     1
1002755     1
1003689     1
           ..
57365208    1
57365760    1
57366313    1
57366865    1
57367417    1
Name: name, Length: 102058, dtype: int64

## 8. Fix outliers

In [413]:
# - Find outliers from int or float type columns
# - If outliers present then replace them with lower or upper limit values
# - Or keep them as it is if they are logical by having outliers

In [414]:
# Check for outliers
for column in df.columns:
    if df[column].dtypes == "int64" or df[column].dtypes == "float64":
        if is_outlier(col=column, df=df):
            print(column)

lat
long
minimum_nights
number_of_reviews

In [415]:
# Check if they should contain outliers or not
df[['lat', 'long', 'minimum_nights', 'number_of_reviews']]

             lat      long  minimum_nights  number_of_reviews
0       40.64749 -73.97237            10.0                9.0
1       40.75362 -73.98377            30.0               45.0
2       40.80902 -73.94190             3.0                0.0
3       40.68514 -73.95976            30.0              270.0
4       40.79851 -73.94399            10.0                9.0
...          ...       ...             ...                ...
102594  40.70862 -73.94651             1.0                0.0
102595  40.80460 -73.96545             1.0                1.0
102596  40.67505 -73.98045             3.0                0.0
102597  40.74989 -73.93777             2.0                5.0
102598  40.76807 -73.98342             1.0                0.0

[102599 rows x 4 columns]

In [416]:
# Column = 'lat'

Q1 = df['lat'].quantile(0.25) # Lower quantile -> 25 %
Q2 = df['lat'].median()       # Median -> 50 %
Q3 = df['lat'].quantile(0.75) # Upper auantile -> 75 %

IQR = Q3 - Q1 # IQR

lower_limit = Q1 - (IQR * 1.5)
upper_limit = Q3 + (IQR * 1.5)

lat_upper_mask = df['lat'] > upper_limit
print(df.loc[lat_upper_mask, 'lat'])

lat_lower_mask = df['lat'] < lower_limit
print(df.loc[lat_lower_mask, 'lat'])

lat_inner_mask = ((df['lat'] >= lower_limit) & (df['lat'] <= upper_limit))
print(df.loc[lat_inner_mask, 'lat'])

262       40.88057
434       40.89747
738       40.89557
967       40.87991
1750      40.88757
            ...
102213    40.91062
102285    40.88354
102300    40.87886
102342    40.87730
102449    40.87633
Name: lat, Length: 622, dtype: float64
1425      40.50868
1630      40.57728
2416      40.57519
3050      40.53884
3762      40.57645
            ...
101501    40.57575
101935    40.53871
102013    40.57577
102014    40.57582
102269    40.56629
Name: lat, Length: 294, dtype: float64
0         40.64749
1         40.75362
2         40.80902
3         40.68514
4         40.79851
            ...
102594    40.70862
102595    40.80460
102596    40.67505
102597    40.74989
102598    40.76807
Name: lat, Length: 101683, dtype: float64

In [417]:
# column = 'long'

Q1 = df['long'].quantile(0.25) # Lower quantile -> 25 %
Q2 = df['long'].median()       # Median -> 50 %
Q3 = df['long'].quantile(0.75) # Upper auantile -> 75 %

IQR = Q3 - Q1 # IQR

lower_limit = Q1 - (IQR * 1.5)
print(lower_limit)

upper_limit = Q3 + (IQR * 1.5)
print(upper_limit)

long_upper_mask = df['long'] > upper_limit
print(df.loc[long_upper_mask, 'long'])

long_lower_mask = df['long'] < lower_limit
print(df.loc[long_lower_mask, 'long'])

long_inner_mask = ((df['long'] >= lower_limit) & (df['long'] <= upper_limit))


print(df.loc[long_inner_mask, 'long'])

-74.057925
-73.857005
144      -73.83168
197      -73.76597
261      -73.85514
262      -73.83572
361      -73.76133
            ...
102438   -73.74834
102440   -73.84868
102450   -73.83029
102504   -73.84962
102584   -73.78990
Name: long, Length: 5584, dtype: float64
170      -74.08088
250      -74.08537
251      -74.08543
252      -74.08546
257      -74.08519
            ...
102181   -74.06337
102191   -74.06789
102269   -74.10331
102289   -74.13113
102451   -74.08390
Name: long, Length: 955, dtype: float64
0        -73.97237
1        -73.98377
2        -73.94190
3        -73.95976
4        -73.94399
            ...
102594   -73.94651
102595   -73.96545
102596   -73.98045
102597   -73.93777
102598   -73.98342
Name: long, Length: 96060, dtype: float64

In [451]:
# Column = 'minimum_nights'

Q1 = df['minimum_nights'].quantile(0.25) # Lower quantile -> 25 %
Q2 = df['minimum_nights'].median()       # Median -> 50 %
Q3 = df['minimum_nights'].quantile(0.75) # Upper auantile -> 75 %

IQR = Q3 - Q1 # IQR

# Lower limit
lower_limit = Q1 - (IQR * 1.5)
print(lower_limit)

# upper limit
upper_limit = Q3 + (IQR * 1.5)
print(upper_limit)

# values which is greater than upper limit in column minimum_nights
print(f"values greater than : {upper_limit}")
nights_upper_mask = df['minimum_nights'] > upper_limit
print(df.loc[nights_upper_mask, 'minimum_nights'])

# values which is lesser than lower limit in column minimum_nights
print(f"Values lesser than {lower_limit}")
nights_lower_mask = df['minimum_nights'] < lower_limit
print(df.loc[nights_lower_mask, 'minimum_nights'])

# Values which falls under the lower and upper range
nights_inner_mask = ((df['minimum_nights'] >= lower_limit) & (df['minimum_nights'] <= upper_limit))
print(df.loc[nights_inner_mask, 'minimum_nights'])

# Replacing negative values with median
df.loc[nights_lower_mask, 'minimum_nights'] = df['minimum_nights'].median()
print(df.loc[nights_lower_mask, 'minimum_nights'])

-2.5
9.5
values greater than : 9.5
0          10.0
1          30.0
3          30.0
4          10.0
6          45.0
          ...
102522     14.0
102528    100.0
102546     21.0
102554     20.0
102577     10.0
Name: minimum_nights, Length: 18383, dtype: float64
Values lesser than -2.5
Series([], Name: minimum_nights, dtype: float64)
2         3.0
5         3.0
8         2.0
9         2.0
10        1.0
         ...
102594    1.0
102595    1.0
102596    3.0
102597    2.0
102598    1.0
Name: minimum_nights, Length: 84216, dtype: float64
Series([], Name: minimum_nights, dtype: float64)

In [442]:
# Column = 'number_of_reviews'

Q1 = df['number_of_reviews'].quantile(0.25) # Lower quantile -> 25 %
Q2 = df['number_of_reviews'].median()       # Median -> 50 %
Q3 = df['number_of_reviews'].quantile(0.75) # Upper auantile -> 75 %

IQR = Q3 - Q1 # IQR

# Lower limit
lower_limit = Q1 - (IQR * 1.5)
print(lower_limit)

# upper limit
upper_limit = Q3 + (IQR * 1.5)
print(upper_limit)

# values which is greater than upper limit in column minimum_nights
reviews_upper_mask = df['number_of_reviews'] > upper_limit
print(df.loc[reviews_upper_mask, 'number_of_reviews'])

# values which is lesser than lower limit in column minimum_nights
reviews_lower_mask = df['number_of_reviews'] < lower_limit
print(df.loc[reviews_lower_mask, 'number_of_reviews'])

-42.5
73.5
3         270.0
5          74.0
8         430.0
9         118.0
10        160.0
          ...
102575    123.0
102579    123.0
102580    209.0
102584     89.0
102588    177.0
Name: number_of_reviews, Length: 11736, dtype: float64
Series([], Name: number_of_reviews, dtype: float64)

## 9. Fix logical intigrity

In [ ]:
# Days/Nights , reviews can not be in float, it have to be converted to integer
df[['minimum_nights', 'number_of_reviews']] = df[['minimum_nights', 'number_of_reviews']].astype(int)

In [453]:
df[['minimum_nights', 'number_of_reviews']]

        minimum_nights  number_of_reviews
0                   10                  9
1                   30                 45
2                    3                  0
3                   30                270
4                   10                  9
...                ...                ...
102594               1                  0
102595               1                  1
102596               3                  0
102597               2                  5
102598               1                  0

[102599 rows x 2 columns]

In [454]:
df

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,1001254,clean quiet apt home by the park,80014485718,unconfirmed,madaline,brooklyn,kensington,40.64749,-73.97237,united states,False,strict,private room,2020.0,966,193,10,9
1,1002102,skylit midtown castle,52335172823,verified,jenna,manhattan,midtown,40.75362,-73.98377,united states,False,moderate,entire homeapt,2007.0,142,28,30,45
2,1002403,the village of harlemnew york,78829239556,unconfirmed,elise,manhattan,harlem,40.80902,-73.94190,united states,True,flexible,private room,2005.0,620,124,3,0
3,1002755,,85098326012,unconfirmed,garry,brooklyn,clinton hill,40.68514,-73.95976,united states,True,moderate,entire homeapt,2005.0,368,74,30,270
4,1003689,entire apt spacious studioloft by central park,92037596077,verified,lyndon,manhattan,east harlem,40.79851,-73.94399,united states,False,moderate,entire homeapt,2009.0,204,41,10,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,spare room in williamsburg,12312296767,verified,krik,brooklyn,williamsburg,40.70862,-73.94651,united states,False,flexible,private room,2003.0,844,169,1,0
102595,6092990,best location near columbia u,77864383453,unconfirmed,mifan,manhattan,morningside heights,40.80460,-73.96545,united states,True,moderate,private room,2016.0,837,167,1,1
102596,6093542,comfy bright room in brooklyn,69050334417,unconfirmed,megan,brooklyn,park slope,40.67505,-73.98045,united states,True,moderate,private room,2009.0,988,198,3,0
102597,6094094,big studioone stop from midtown,11160591270,unconfirmed,christopher,queens,long island city,40.74989,-73.93777,united states,True,strict,entire homeapt,2015.0,546,109,2,5
102598,6094647,sf luxury studio,68170633372,unconfirmed,rebecca,manhattan,upper west side,40.76807,-73.98342,united states,False,flexible,entire homeapt,2010.0,1032,206,1,0

## 10. Save cleaned dataset

In [462]:
df.to_csv('../data/cleaned_airbnb.csv', index=False)