In [68]:
# - import libraries
# - load dataset
# - explore dataset

# - fix column names
# - fix individual columns

# - fix nulls in all type of columns
# - fix duplicates in all type of columns
# - fix outliers
# - fix logical intigrity
# - final exploration
# - save cleaned data

## 1 - import libraries

In [69]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 2 - load dataset

In [70]:
df = pd.read_csv(r"C:\Users\Arijit\Downloads\messy_customer_sales_data.csv")
df

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0 years,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62.0,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40.0,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41.0,CHENNAI,2024-04-05,2024-12-15,NaN,8.0,denise84@example.org,2665569480,India
...,...,...,...,...,...,...,...,...,...,...,...,...
10195,CUST10767,Robert Lewis,female,35.0 years,delhi,2020-12-08,2025-01-25,24167.0,9.0,barrycrane@example.net,5004696571,InDia
10196,NaN,Diane Evans,M,53.0,bangalore,2023-12-31,2025-05-07,11639.0,7.0,lisadennis@example.net,5200349941,IND
10197,CUST6315,Joshua Martinez,m,25.0,hyderabad,2022-02-15,2025-01-11,43832.0,2.0,kelli74@example.org,8147428496,India
10198,CUST4812,Sarah Miller,FEMALE,55.0,NaN,2021-03-16,2025-05-14,18827.0,10.0,dawn84@example.org,2987564247,InDia
10199,CUST6588,David Potter,female,34.0,HYDERABAD,2020-10-12,2025-06-27,35211.0,10.0,kochjonathan@example.org,1926206725,India

## 3 - explore dataset

In [71]:
print("Total rows : ", df.shape[0])
print("Total column : ", df.shape[1])
print("Dataset dimension : ", df.ndim)

print()

print(df.info())
df.describe()

Total rows :  10200
Total column :  12
Dataset dimension :  2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9177 non-null   object
 1   Name                10200 non-null  object
 2   Gender              9174 non-null   object
 3   Age                 9249 non-null   object
 4   City                9184 non-null   object
 5   Signup_Date         10200 non-null  object
 6   Last_Purchase_Date  9188 non-null   object
 7   Purchase_Amount     9179 non-null   float64
 8   Feedback_Score      9177 non-null   float64
 9   Email               10200 non-null  object
 10  Phone_Number        10200 non-null  int64
 11  Country             9468 non-null   object
dtypes: float64(2), int64(1), object(9)
memory usage: 956.4+ KB
None

       Purchase_Amount  Feedback_Score  Phone_Number
count     9.179000e+03     9177.000000  1.020000e+04
mean      2.909013e+04        5.479351  4.979974e+09
std       2.086971e+05        2.867123  2.902593e+09
min      -5.000000e+02        1.000000  9.208990e+05
25%       1.229500e+04        3.000000  2.449157e+09
50%       2.433000e+04        5.000000  4.988639e+09
75%       3.713000e+04        8.000000  7.510448e+09
max       9.999999e+06       10.000000  9.994402e+09

## 4 - fix column names

In [72]:
# print all columns
print(df.columns)

# Check how many columns are present
print(len(df.columns))

print()
# check for inconsistancy

# Check for special characters
print("\nCheck for special characters")
print(df.columns[df.columns.str.contains(r'[^A-Za-z0-9]')])


# Check for leading or trailing spaces
print("\nCheck for leading or trailing spaces")
print(df.columns[df.columns != df.columns.str.strip()])

# Check for inner spaces
print("\nCheck for inner spaces")
print(df.columns[df.columns.str.contains(r' ')])

# Check for numbers
print("\nCheck for numbers")
print(df.columns[df.columns.str.contains(r'[0-9]')])

# check for upper case letters
print("\ncheck for upper case letters")
print(df.columns[df.columns != df.columns.str.lower()])

Index(['Customer_ID', 'Name', 'Gender', 'Age', 'City', 'Signup_Date',
       'Last_Purchase_Date', 'Purchase_Amount', 'Feedback_Score', 'Email',
       'Phone_Number', 'Country'],
      dtype='object')
12


Check for special characters
Index(['Customer_ID', 'Signup_Date', 'Last_Purchase_Date', 'Purchase_Amount',
       'Feedback_Score', 'Phone_Number'],
      dtype='object')

Check for leading or trailing spaces
Index([], dtype='object')

Check for inner spaces
Index([], dtype='object')

Check for numbers
Index([], dtype='object')

check for upper case letters
Index(['Customer_ID', 'Name', 'Gender', 'Age', 'City', 'Signup_Date',
       'Last_Purchase_Date', 'Purchase_Amount', 'Feedback_Score', 'Email',
       'Phone_Number', 'Country'],
      dtype='object')

In [73]:
# Fix 
# Convert all columns to lower case letters
df.columns = df.columns.str.lower()

# Final check
print(df.columns)

Index(['customer_id', 'name', 'gender', 'age', 'city', 'signup_date',
       'last_purchase_date', 'purchase_amount', 'feedback_score', 'email',
       'phone_number', 'country'],
      dtype='object')

## 5 - fix individual columns

In [74]:
# Fix object type columns first
for column in df.columns:
    if df[column].dtype == "object":
        print(column)

customer_id
name
gender
age
city
signup_date
last_purchase_date
email
country

In [75]:
# 'customer_id' is a primary key column so it can not contain any null values and duplicates
print((df['customer_id'].isnull().sum()/len(df['customer_id']))*100) # 10 % missing
print(df['customer_id'].duplicated().sum()/len(df['customer_id'])*100)

print(df['customer_id'].isnull().sum())
print(df['customer_id'].duplicated().sum())

# Droping rows which contain nulls
df.dropna(subset=['customer_id'], inplace=True)

# Droping rows which contains duplicates
df.drop_duplicates(subset=['customer_id'], inplace=True)

# Final check
print((df['customer_id'].isnull().sum()/len(df['customer_id']))*100) # 0 % missing
print(df['customer_id'].duplicated().sum()/len(df['customer_id'])*100) # 0 % duplicates

10.029411764705882
11.754901960784315
1023
1199
0.0
0.0

In [76]:
# 'name'

# Check Total special characters
print("Total special characters : ", df['name'].str.contains(r'[^A-Za-z0-9\s]', regex=True, na=False).sum())

# Check for numbers
print("Total numbers : ", df['name'].str.contains(r'[0-9]', regex=True, na=False).sum())

# Check for new lines 
print("Total new lines : ", df['name'].str.contains(r'\n', regex=True, na=False).sum())

# Check for upper case letters
print("Total upper case letters : ", df['name'].str.contains(r'[A-Z]', regex=True, na=False).sum())

# Leading or trailing spaces
mask_space = df['name'] != df['name'].str.strip()
print("Total leading or trailing spaces : ", mask_space.sum())

Total special characters :

 181
Total numbers :  0
Total new lines :  0
Total upper case letters :  9000
Total leading or trailing spaces :  0

In [77]:
# Fix 
df['name'] = (
    df['name']
    .str.lower()
    .str.replace(r'[^a-z\s]', '', regex=True)
)

In [78]:
# Final check

# Check Total special characters
print("Total special characters : ", df['name'].str.contains(r'[^A-Za-z0-9\s]', regex=True, na=False).sum())

# Check for upper case letters
print("Total upper case letters : ", df['name'].str.contains(r'[A-Z]', regex=True, na=False).sum())

Total special characters :  0
Total upper case letters :  0

In [79]:
# 'gender'
print(df['gender'].value_counts())
print(df['gender'].unique())

# Fix
df['gender'] = df['gender'].replace(
    {
        "m ":"male",
        "M":"male",
        "MALE":"male",
        "F":"female",
        "FEMALE":"female",
        "f ":"female"
    }
)

# Final check
print(df['gender'].value_counts())
print(df['gender'].unique())

gender
M         1042
f         1037
m         1031
F         1028
MALE       993
male       989
female     989
FEMALE     982
Name: count, dtype: int64
['m ' 'M' 'F' 'FEMALE' 'f ' 'male' 'MALE' 'female' nan]
gender
male      4055
female    4036
Name: count, dtype: int64
['male' 'female' nan]

In [80]:
# city
print(df['city'].value_counts())
print(df['city'].unique())

# Fix
df['city'] = (
    df['city']
    .str.lower()
    .str.strip()
)

# Check
print(df['city'].value_counts())
print(df['city'].unique())

city
Kolkata       719
Mumbai        709
Chennai       688
Delhi         685
Bangalore     675
Hyderabad     661
CHENNAI       367
DELHI         346
MUMBAI        343
hyderabad     342
bangalore     342
KOLKATA       336
HYDERABAD     334
delhi         321
BANGALORE     320
mumbai        308
chennai       302
kolkata       297
Name: count, dtype: int64
[' KOLKATA ' nan ' hyderabad ' ' CHENNAI ' ' kolkata ' ' BANGALORE '
 ' Hyderabad ' ' HYDERABAD ' ' Mumbai ' ' chennai ' ' Delhi '
 ' bangalore ' ' Bangalore ' ' Kolkata ' ' delhi ' ' Chennai ' ' MUMBAI '
 ' DELHI ' ' mumbai ']
city
mumbai       1360
chennai      1357
delhi        1352
kolkata      1352
hyderabad    1337
bangalore    1337
Name: count, dtype: int64
['kolkata' nan 'hyderabad' 'chennai' 'bangalore' 'mumbai' 'delhi']

In [81]:
# signup_date
print(df['signup_date'].dtypes)

df['signup_date'] = pd.to_datetime(df['signup_date'], errors='coerce')
print(df['signup_date'].dtypes)

object
datetime64[ns]

In [82]:
# last_purchase_date
print(df['last_purchase_date'].dtypes)
df['last_purchase_date'] = pd.to_datetime(df['last_purchase_date'], errors='coerce')
print(df['last_purchase_date'].dtypes)

object
datetime64[ns]

In [83]:
# email
# email type : abc@gmail.com / abc12@gmail.com
# Basic cleaning

df['email'] = (
    df['email']
    .str.lower()
    .str.strip()
    .str.replace(r'[^0-9a-z@.]', '', regex=True)
)

In [84]:
# country
print(df['country'].value_counts())
print(df['country'].unique())

# Fix
valid_pattern = {
    "India":"india",
    "IND":"india",
    "InDia":"india"
}

df['country'] = df['country'].map(valid_pattern)

# final check
print(df['country'].value_counts())
print(df['country'].unique())

country
India    6303
IND       687
india     678
InDia     678
Name: count, dtype: int64
['India' 'india' nan 'InDia' 'IND']
country
india    7668
Name: count, dtype: int64
['india' nan]

In [85]:
# 'age'
df['age'] = df['age'].str.lower()                              # to lower case
df['age'] = df['age'].str.replace(r'[a-z\s]', '', regex=True)  # replacing letters and spaces with empty string
df['age'] = df['age'].replace('', np.nan)                      # replacing empty string with NaN (Nulls)
df['age'] = df['age'].replace(np.nan, df['age'].mode()[0])     # replacing nulls with most frequent values
df['age'] = df['age'].astype(float).astype(int)                # converting data type from str to float to int

In [86]:
# Now int or float type columns
for column in df.columns:
    if df[column].dtypes == "int64" or df[column].dtypes == "float64":
        print(column)

age
purchase_amount
feedback_score
phone_number

In [87]:
# Check outliers
def is_outlier(col: str, df: pd.DataFrame) -> bool:

    Q1 = df[col].quantile(0.25)
    Q2 = df[col].median()
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - (IQR * 1.5)
    upper_limit = Q3 + (IQR * 1.5)

    if len(df.loc[df[col] > upper_limit]) > 0 or len(df.loc[df[col] < lower_limit]) > 0:
        return True
    else:
        return False

In [88]:
# purchase_amount
print((df[['purchase_amount', 'feedback_score']].isnull().sum()/len(df[['purchase_amount', 'feedback_score']]))*100)

# Fix
columns = ['purchase_amount', 'feedback_score']

for cols in columns:
    if is_outlier(col=cols, df=df):
        df[cols] = df[cols].replace(np.nan, df[cols].median())
    else:
        df[cols] = df[cols].replace(np.nan, df[cols].mean())

# Final check
print((df[['purchase_amount', 'feedback_score']].isnull().sum()/len(df[['purchase_amount', 'feedback_score']]))*100)

purchase_amount    10.066667
feedback_score      9.855556
dtype: float64
purchase_amount    0.0
feedback_score     0.0
dtype: float64

In [89]:
# phone number
# For data cleaning
# If you're cleaning the dataset, don't treat phone number as an integer.

# To check in phone numbers
# This is important because phone numbers can have:
"""
# leading zeros
# country codes (+91)
# spaces
# hyphens
# parentheses
"""

# convert it's data type for better analysis
df['phone_number'] = df['phone_number'].astype(str)

# Leading zeros
zeros_mask = df['phone_number'].str.startswith('0', na=False)
print(zeros_mask.sum())

# country code (+91)
country_code_mask = df['phone_number'].str.startswith('+91', na=False)
print(country_code_mask.sum())

# length > 10
greater_than_ten_mask = df['phone_number'].str.len() > 10
print(greater_than_ten_mask.sum())


df['phone_number'] = df['phone_number'].astype(int)

0
0
0

In [90]:
df

,customer_id,name,gender,age,city,signup_date,last_purchase_date,purchase_amount,feedback_score,email,phone_number,country
0,CUST4371,paul wilson,male,52,kolkata,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,india
1,CUST5957,jason thomas,male,51,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,NaN
2,CUST3754,brittney martinez,female,62,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,india
3,CUST2934,brenda pierce,female,40,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,NaN
4,CUST5683,matthew carroll,female,41,chennai,2024-04-05,2024-12-15,24268.0,8.0,denise84@example.org,2665569480,india
...,...,...,...,...,...,...,...,...,...,...,...,...
10193,CUST6352,isaiah terry,female,26,kolkata,2023-03-04,2025-06-30,43655.0,6.0,lopezleonard@example.net,7694723210,india
10194,CUST6146,cody thompson,female,40,NaN,2024-08-21,2024-10-26,35101.0,1.0,mitchellrivera@example.net,6380823112,india
10195,CUST10767,robert lewis,female,35,delhi,2020-12-08,2025-01-25,24167.0,9.0,barrycrane@example.net,5004696571,india
10197,CUST6315,joshua martinez,male,25,hyderabad,2022-02-15,2025-01-11,43832.0,2.0,kelli74@example.org,8147428496,india
10198,CUST4812,sarah miller,female,55,NaN,2021-03-16,2025-05-14,18827.0,10.0,dawn84@example.org,2987564247,india

# 6 - fix nulls in all type of columns

In [91]:
# Object type columns
for column in df.columns:
    if df[column].dtypes == "object":
        if column == "email":
            continue
        else:
            missing_pct = (df[column].isnull().sum()/len(df[column]))*100
            if missing_pct <= 10:
                df[column] = df[column].replace(np.nan, df[column].mode()[0])
            else:
                df[column] = df[column].replace(np.nan, 'unknown')

In [92]:
# Data type columns
for column in df.columns:
    if df[column].dtypes == '<M8[ns]':
        missing_pct = (df[column].isnull().sum()/len(df[column]))*100

        if missing_pct <= 50:
            df[column] = df[column].ffill()

In [93]:
# final check
df.isnull().sum()

customer_id           0
name                  0
gender                0
age                   0
city                  0
signup_date           0
last_purchase_date    0
purchase_amount       0
feedback_score        0
email                 0
phone_number          0
country               0
dtype: int64

## 7 - fix outliers

In [94]:
for column in df.columns:
    if df[column].dtypes == "int64" or df[column].dtypes == "float64":
        if is_outlier(col=column, df=df):
            print(column)

age
purchase_amount

In [95]:
# 'age'

Q1 = df['age'].quantile(0.25)   # 25th quantile
Q2 = df['age'].median()         # Median
Q3 = df['age'].quantile(0.75)   # 75th quantile
    
IQR = Q3 - Q1   # Inter Quartile Range

lower_limit = Q1 - (IQR * 1.5)  # lower limit
print(lower_limit)
upper_limit = Q3 + (IQR * 1.5)  # upper limit
print(upper_limit)

-11.5
104.5

In [96]:
df.loc[df['age'] > upper_limit]

,customer_id,name,gender,age,city,signup_date,last_purchase_date,purchase_amount,feedback_score,email,phone_number,country
470,CUST6977,tyler stout,female,250,chennai,2022-05-21,2025-05-31,3554.0,2.0,hudsonsandra@example.net,5752427586,india
932,CUST1207,cathy robinson,female,250,delhi,2024-10-24,2025-10-01,23012.0,6.0,jefftaylor@example.org,1244788430,unknown
5279,CUST4536,alexandra ramos,male,250,chennai,2021-09-30,2025-03-03,3296.0,10.0,drakemichelle@example.org,5651607326,india
5949,CUST7041,joseph young,male,250,delhi,2022-01-20,2024-11-26,1131.0,8.0,pmckenzie@example.org,9456700786,india
6085,CUST8110,betty cole,female,250,bangalore,2024-01-07,2025-04-12,25974.0,1.0,dmitchell@example.net,366613689,india
6615,CUST10236,brittney boyd,male,250,kolkata,2022-04-01,2024-12-25,17284.0,3.0,andrewcraig@example.org,3843232885,india
7752,CUST5388,lauren smith,male,250,chennai,2024-12-20,2024-10-17,43258.0,6.0,hernandezdonna@example.org,5886842393,india

In [97]:
df.loc[df['age'] < lower_limit]

Empty DataFrame
Columns: [customer_id, name, gender, age, city, signup_date, last_purchase_date, purchase_amount, feedback_score, email, phone_number, country]
Index: []

In [98]:
df.loc[df['age'] < 0]

,customer_id,name,gender,age,city,signup_date,last_purchase_date,purchase_amount,feedback_score,email,phone_number,country
2702,CUST1941,virginia casey,male,-10,chennai,2022-09-22,2025-01-12,3056.0,2.0,mallen@example.com,1007163131,india
7720,CUST3810,meredith shaw,male,-10,kolkata,2024-05-21,2025-07-03,6126.0,1.0,ukerr@example.com,2923214533,india
8337,CUST8792,mark meyer,female,-10,delhi,2022-03-29,2025-04-09,22740.0,1.0,tylernichols@example.org,2911495286,india

In [ ]:
# Fixing lower limit first
lower_mask = df['age'] < 0
df.loc[lower_mask, 'age'] = -(df.loc[lower_mask, 'age'])

Series([], Name: age, dtype: int64)

In [ ]:
# fixing upper limit
upper_mask = df['age'] > upper_limit
df.loc[upper_mask, 'age'] = upper_limit

In [109]:
# Final check
print(is_outlier(col='age', df=df))

False

In [110]:
# purchase_amount
Q1 = df['purchase_amount'].quantile(0.25)   # 25th quantile
Q2 = df['purchase_amount'].median()         # Median
Q3 = df['purchase_amount'].quantile(0.75)   # 75th quantile
    
IQR = Q3 - Q1   # Inter Quartile Range

lower_limit = Q1 - (IQR * 1.5)  # lower limit
print(lower_limit)
upper_limit = Q3 + (IQR * 1.5)  # upper limit
print(upper_limit)

-18931.875
68433.125

In [112]:
# upper limit
df.loc[df['purchase_amount'] > upper_limit]

,customer_id,name,gender,age,city,signup_date,last_purchase_date,purchase_amount,feedback_score,email,phone_number,country
2383,CUST3987,erica johnson,male,47.0,kolkata,2020-11-03,2025-08-10,9999999.0,5.0,bflowers@example.com,747807729,unknown
3368,CUST7314,gavin yates,male,50.0,bangalore,2022-06-30,2025-03-22,9999999.0,10.0,millermichael@example.com,1481715956,india
4674,CUST8481,denise combs,female,62.0,mumbai,2024-10-06,2025-07-08,9999999.0,3.0,cmorales@example.net,2931912910,unknown
4692,CUST10561,richard brown,female,58.0,mumbai,2024-04-13,2025-09-08,9999999.0,2.0,kevintaylor@example.net,7047881855,india

In [114]:
# lower limit
df.loc[df['purchase_amount'] < 0]

,customer_id,name,gender,age,city,signup_date,last_purchase_date,purchase_amount,feedback_score,email,phone_number,country
28,CUST9655,kara estrada,male,52.0,delhi,2022-09-09,2025-08-27,-500.0,4.0,markturner@example.org,4191684631,india
68,CUST7413,anthony simmons,male,62.0,kolkata,2023-08-10,2024-11-01,-500.0,3.0,andersonleslie@example.com,6860283096,india
722,CUST10196,sally thomas,female,32.0,kolkata,2024-10-19,2025-07-20,-500.0,5.0,rosalesanna@example.net,4360772751,india
1630,CUST10114,christina fletcher,male,66.0,delhi,2024-11-18,2025-08-16,-500.0,3.0,lorimoses@example.org,8932569887,india

In [116]:
# fix
# fixing lower limit
lower_mask = df['purchase_amount'] < 0
df.loc[lower_mask, 'purchase_amount'] = - (df.loc[lower_mask, 'purchase_amount'])

In [120]:
# fixing upper limit
upper_mask = df['purchase_amount'] > upper_limit
df.loc[upper_mask, 'purchase_amount'] = upper_limit

In [122]:
# check
print(is_outlier(col='purchase_amount', df=df))

False

## 8 - fix logical intigrity

In [124]:
df[['signup_date', 'last_purchase_date']]

      signup_date last_purchase_date
0      2025-06-26         2025-05-17
1      2021-02-17         2025-07-22
2      2023-11-05         2024-12-08
3      2022-03-13         2025-10-02
4      2024-04-05         2024-12-15
...           ...                ...
10193  2023-03-04         2025-06-30
10194  2024-08-21         2024-10-26
10195  2020-12-08         2025-01-25
10197  2022-02-15         2025-01-11
10198  2021-03-16         2025-05-14

[9000 rows x 2 columns]

In [133]:
# sign up date can not be greater than last purchase date
# it is an logical intigrity error
time_travel_mask = df['signup_date'] > df['last_purchase_date']
df.loc[time_travel_mask, 'last_purchase_date'] = df.loc[time_travel_mask, 'signup_date'] + pd.Timedelta(days=30)

In [135]:
# final check
time_travel_mask.sum()

np.int64(0)

In [142]:
# age can not be in float
df['age'] = df['age'].astype(int)

In [143]:
df

,customer_id,name,gender,age,city,signup_date,last_purchase_date,purchase_amount,feedback_score,email,phone_number,country
0,CUST4371,paul wilson,male,52,kolkata,2025-06-26,2025-07-26,26944.0,1.0,peckvictoria@example.com,2131107701,india
1,CUST5957,jason thomas,male,51,unknown,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,unknown
2,CUST3754,brittney martinez,female,62,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,india
3,CUST2934,brenda pierce,female,40,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,unknown
4,CUST5683,matthew carroll,female,41,chennai,2024-04-05,2024-12-15,24268.0,8.0,denise84@example.org,2665569480,india
...,...,...,...,...,...,...,...,...,...,...,...,...
10193,CUST6352,isaiah terry,female,26,kolkata,2023-03-04,2025-06-30,43655.0,6.0,lopezleonard@example.net,7694723210,india
10194,CUST6146,cody thompson,female,40,unknown,2024-08-21,2024-10-26,35101.0,1.0,mitchellrivera@example.net,6380823112,india
10195,CUST10767,robert lewis,female,35,delhi,2020-12-08,2025-01-25,24167.0,9.0,barrycrane@example.net,5004696571,india
10197,CUST6315,joshua martinez,male,25,hyderabad,2022-02-15,2025-01-11,43832.0,2.0,kelli74@example.org,8147428496,india
10198,CUST4812,sarah miller,female,55,unknown,2021-03-16,2025-05-14,18827.0,10.0,dawn84@example.org,2987564247,india

## 9 - final exploration

In [146]:
# check how many not null values are present
print(df.notna().sum())

print("\n\n")

# Final exploration
print(df.info())

print("\n\n")

# Final summary statistics
df.describe()

customer_id           9000
name                  9000
gender                9000
age                   9000
city                  9000
signup_date           9000
last_purchase_date    9000
purchase_amount       9000
feedback_score        9000
email                 9000
phone_number          9000
country               9000
dtype: int64



<class 'pandas.core.frame.DataFrame'>
Index: 9000 entries, 0 to 10198
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         9000 non-null   object
 1   name                9000 non-null   object
 2   gender              9000 non-null   object
 3   age                 9000 non-null   int64
 4   city                9000 non-null   object
 5   signup_date         9000 non-null   datetime64[ns]
 6   last_purchase_date  9000 non-null   datetime64[ns]
 7   purchase_amount     9000 non-null   float64
 8   feedback_score      9000 non-null   float64
 9   email               9000 non-null   object
 10  phone_number        9000 non-null   int64
 11  country             9000 non-null   object
dtypes: datetime64[ns](2), float64(2), int64(2), object(6)
memory usage: 914.1+ KB
None

,age,signup_date,last_purchase_date,purchase_amount,feedback_score,phone_number
count,9000.000000,9000,9000,9000.000000,9000.000000,9.000000e+03
mean,45.768222,2023-04-12 05:12:00,2025-04-24 01:18:14.399999744,24668.363611,5.481326,4.983041e+09
min,3.000000,2020-10-08 00:00:00,2024-10-08 00:00:00,0.000000,1.000000,9.208990e+05
25%,32.000000,2022-01-17 18:00:00,2025-01-25 00:00:00,13830.000000,3.000000,2.449808e+09
50%,46.000000,2023-04-05 00:00:00,2025-05-01 00:00:00,24268.000000,5.481326,4.998591e+09
75%,61.000000,2024-07-12 00:00:00,2025-07-25 00:00:00,35671.250000,8.000000,7.510124e+09
max,104.000000,2025-10-08 00:00:00,2025-11-07 00:00:00,68433.125000,10.000000,9.994402e+09
std,15.807433,NaN,NaN,13652.321850,2.718595,2.901555e+09

## 10 - save cleaned data

In [149]:
df.to_csv("../data/cleaned_customers.csv", index=False)
print("Saved")

Saved